// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skwkufybtzvvigkgnxbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrd2t1ZnlidHp2dmlna2dueGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzU1MDUsImV4cCI6MjA3MTAxMTUwNX0.8CMnBG3NP-i_KbiSSUWQIowqXFNwFtOsQWw8PiI-7a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});